#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# make all windows layer normal
yabai -m rule --add app=".*" layer=normal

# space windows
yabai -m rule --add app="^Messages$" space=1
yabai -m rule --add app="^FaceTime$" space=1
yabai -m rule --add app="^WeChat$" space=1
yabai -m rule --add app="^Discord$" space=1
yabai -m rule --add app="^Slack$" space=1
yabai -m rule --add app="^WhatsApp$" space=1
yabai -m rule --add app="^zoom.us$" space=1

yabai -m rule --add app="^SelfControl$" space=2
yabai -m rule --add app="^Calendar$" space=2
yabai -m rule --add app="^Mail$" space=2
yabai -m rule --add app="^Reminders$" space=2
yabai -m rule --add app="^Notes$" space=2

# ignored apps
yabai -m rule --add app="^(Installer|Software Update|The Unarchiver|MediaMate)$" manage=off layer=below

global settings

yabai -m config                              \
    mouse_follows_focus         off          \
    focus_follows_mouse         off          \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               off          \
    window_animation_duration   0.0          \
    window_opacity_duration     0.0          \
    active_window_opacity       1.0          \
    normal_window_opacity       1.0          \
    window_opacity              off          \
    insert_feedback_color       0xaad75f5f   \
    active_window_border_color  0xBF775759   \
    normal_window_border_color  0x7f353535   \
    window_border_width         3            \
    window_border_radius        9            \
    window_border_blur          on           \
    window_border_hidpi         on           \
    window_border               off          \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    mouse_modifier              fn           \
    mouse_action1               resize       \
    mouse_action2               resize       \
    mouse_drop_action           swap

# layout settings
yabai -m config layout                       float
# yabai -m config top_padding                  10
# yabai -m config bottom_padding               10
# yabai -m config left_padding                 10
# yabai -m config right_padding                10
# yabai -m config window_gap                   10
# yabai -m config external_bar                 all:00:00 # all:35:00

# signals for window focus
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

echo "yabai configuration loaded.."
